### ISSUE TITLE
Trin 0: Opret profil

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/recommender-feedback#10]
Brugeren skal kunne oprette en profil med email og password.
Undersøg om vi (DBC) i forvejen har en email-verifikationsfunktionalitet, der kan genbruges i dette projekt.

**Comment by kfudbc** [comment]
React komponent er lavet. Forbindelse med endpoint etableres i https://github.com/DBCDK/recommender-feedback/issues/37

**Comment by KiraH** [comment]
testet OK
