### ISSUE TITLE
Trin 1: Søgeside

### ISSUE THREAD

**Issue by KiraH** [DBCDK/recommender-feedback#16]
Der skal oprettes en søgeside, hvor brugeren kan fremsøge et værk.
Klik på et værk fører brugeren over til visning af anbefalinger, dvs. trin 2.
Se AFB design.

**Comment by kfudbc** [comment]
React komponent er lavet. Forbindelse med endpoint etableres i https://github.com/DBCDK/recommender-feedback/issues/37

**Comment by KiraH** [comment]
testet OK
