### ISSUE TITLE
Trin 0: Login

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/recommender-feedback#18]
Brugeren skal kunne logge ind med email og password

**Comment by jpsecher** [comment]
To avoid remembering yet another password, as a user, I just want to use my email address and get a link in an email that will log me in the system automatically.

**Comment by kfudbc** [comment]
Så er løsningen at:
- bruger tilmelder sig med email
- system genererer unik url til denne brugere og sender til email
- system persisterer unik-url-email mapning

**Comment by kfudbc** [comment]
Dette er react-komponenten. Samspil med endpoints ligger i https://github.com/DBCDK/recommender-feedback/issues/37

**Comment by KiraH** [comment]
testet OK
