### ISSUE TITLE
Floodfiltering af anbefalinger

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/recommender-feedback#27]
For at undgå anbefalinger med samme forfatter, som man har søgt på.

**Comment by cboesgaard** [comment]
Løsning i grænsefladen: når der hentes anbefalinger for pid_x med creator_x, så skal alle anbefalinger af creator_x fjernes fra anbefalingerne før de præsenteres.

Det vil ikke virke perfekt, men være en fin løsning for nu.

**Comment by KiraH** [comment]
Testet OK
