### ISSUE TITLE
Endpoint: profil-håndtering

### ISSUE THREAD

**Issue by kfudbc** [DBCDK/recommender-feedback#32]
Vi har brug for endpoints til profilhåndtering:

- Endpoint til at tilmelde sig. Endpoint sørger for at sende email, samt at oprette bruger med et profil-id.
input: email-adresse
output: Status-besked

- Endpoint til validering af profil-id
input: profil-id
output: status + brugerens email

**Comment by jpsecher** [comment]
kfudbc skrev: *Sådan fik jeg sendt en mail. host skal så være konfigurerbar med miljøvariabel:*

```
const nodemailer = require('nodemailer');

let transporter = nodemailer.createTransport({
  host: 'mailhost.dbc.dk',
  port: 25,
  secure: false,
});

// setup email data with unicode symbols
let mailOptions = {
  from: '"KF" <kfu@dbc.dk>', // sender address
  to: 'kfu@dbc.dk', // list of receivers
  subject: 'Hej - test', // Subject line
  text: 'Dette er en test' // plain text body
};

transporter.sendMail(mailOptions, (error, info) => {
  if (error) {
    return console.log(error);
  }
  console.log('Message sent: %s', info.messageId);
});
```
