### ISSUE TITLE
Rettelser / bugs pr. 9. okt.

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/recommender-feedback#42]
- [x] Der søges helt bredt og på mange sprog - er dansk  (og evt. engelsk) ikke nok til give et solidt datasæt?
- [ ] Der kommer også søgeresultater fra fx blindebiblioteket - kan vi ikke indstille søgningen lidt smallere vha en anden søgeprofil?
- [x]  Trin 2: Stjerner og ?-ikon skal være lys grå i udgangspunktet. ?-ikonet skal blive sort, når det er valgt.
- [x]  Trin 2: Tom linie ml. emneord og forlag/årstal
- [ ]  Trin 2: Komma ml. sideantal og antal bind
- [x]  Trin 2: Link til bibliotek.dk skal gå til værkets side, fx: https://bibliotek.dk/da/work/870970-basis:25142594 
- [x]  Indsæt spinner ved søgning (trin 1) og anbefaling (trin 2)
- [x]  Trin 1: Når man har trykket prøv igen og kommer tilbage til søgningen, skal man ikke se det tidligere søgeresultat.
- [ ]  Trin 2: Fik ved søgning på Doppler af Erlend Loe anbefalet en bog ugen titel af Ed Brubaker. Bogen  findes ikke i bibliotek.dk: 870970-basis:40252800 vha. det indsatte link i grænsefladen. Hvordan er den anbefaling dukket op?

**Comment by BettinaAndersen** [comment]
Åbne elementer blev nedprioriterede ved planning 24-10-2017
