### ISSUE TITLE
Tekstændringer 

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/recommender-feedback#46]
Læsekompas-gruppen ønsker at ændre nogle tekstformuleringer.

**Comment by BettinaAndersen** [comment]
Tekstændringer fra Læsekompasset:
https://www.dropbox.com/s/nwle6mhwza5awmu/tekstrettelser-bedre-forslag-cec-06-11-17.docx?dl=0

**Comment by KiraH** [comment]
testet OK
