### ISSUE TITLE
Trin 2: Se anbefalinger fra recommender

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/recommender-feedback#6]
Se liste over anbefalinger baseret på det valgte værk, incl. titel, forfatter og forsidebillede.
Desuden udfoldning af indholdsnote, forlag, årstal og emneord.
Se AFB design.

**Comment by kfudbc** [comment]
React komponent er lavet. Forbindelse med endpoint etableres i https://github.com/DBCDK/recommender-feedback/issues/37

**Comment by KiraH** [comment]
Det er ikke muligt at udfolde indholdsnote, forlag, årstal og emneord.

**Comment by BettinaAndersen** [comment]
Testet og godkendt
